#!/bin/bash

# Alt+# to show line numbers
# This script will present the user with a command line menu.
# This menuw ill allow the user to select from AddBiz, RmBiz and FindBiz 
# This will also allow the user to email any or all of the companies listed in the Address Book

# chmod 755 Menu to give execute permissions on file
echo
echo
echo "Welcome to AddressBook"
echo "----------------------"
echo
# Create variables with the script to execute for each option

SCRIPT_ADDBIZ="./AddBiz"
SCRIPT_REMBIZ="./RmBiz"
SCRIPT_FINDBIZ="./FindBiz"



options=("Add a Business" "Remove a Business" "Find a Business" "Quit")
PS3='Choose a number to select the option: '



select opt in "${options[@]}"
do

echo

	case $REPLY  in
	1)
		echo "You have chosen to Add a Business"
			echo
			echo "Please enter the Company Name:"
			read companyName
			echo
			echo "Please enter the Business Contacts Full Name:"
			read contactName
			echo
			echo "Please enter their address:"
			read address
			echo
			echo "Please enter their phone number:"
			read phoneNumber
			echo
			echo "Please enter their email address:"
			read email
			echo
			echo "The details you entered are $companyName , $contactName , $address , $phoneNumber , $email  "
			echo "Adding to the AddressBook now.."
		#Call the AddBiz file 
		exec $SCRIPT_ADDBIZ "$companyName" "$contactName" "$address" "$phoneNumber" "$email"
		;;
	2)
		echo "You have chosen to Remove a Business"
		exec $SCRIPT_REMBIZ
		;;
	3)
		echo "You have chosen to Find a Business"
		exec $SCRIPT_FINDBIZ
		;;
	4)	echo "GoodBye!"
		break
		;;
	*) echo "invalid option $REPLY";;
	esac
done

