#!/bin/bash

# Alt+# to show line numbers
# This script will present the user with a command line menu.
# This menuw ill allow the user to select from AddBiz, RmBiz and FindBiz 
# This will also allow the user to email any or all of the companies listed in the Address Book

# chmod 755 Menu to give execute permissions on file
echo
echo
echo "Welcome to AddressBook"
echo "----------------------"
echo
# Create variables with the script to execute for each option

SCRIPT_ADDBIZ="./AddBiz"
SCRIPT_REMBIZ="./RmBiz"
SCRIPT_FINDBIZ="./FindBiz"



main_options=("Add a Business" "Remove a Business" "Find a Business" "Quit")
search_options=("Search by Business Name" "Search by Contact Name" "Search by Address" "Search by Phone Number" "Search by Email" "Return to Main Menu" ) 
PS3='Choose a number to select the option: '



select opt in "${main_options[@]}"
do

echo

	case $REPLY  in
	1)
		echo "You have chosen to Add a Business"
			echo
			echo "Please enter the Company Name:"
			read companyName
			echo
			echo "Please enter the Business Contacts Full Name:"
			read contactName
			echo
			echo "Please enter their address:"
			read address
			echo
			echo "Please enter their phone number:"
			read phoneNumber
			echo
			echo "Please enter their email address:"
			read email
			echo
			echo "The details you entered are $companyName , $contactName , $address , $phoneNumber , $email  "
			echo "Adding to the AddressBook now.."
		#Call the AddBiz file 
		exec $SCRIPT_ADDBIZ "[$companyName]" "[$contactName]" "[$address]" "[$phoneNumber]" "[$email]"
		;;
	2)
		echo "You have chosen to Remove a Business"
		exec $SCRIPT_REMBIZ
		;;
	3)
		echo "You have chosen to Find a Business"
		echo
		echo
		# Sub Menu to select the search criteria
		select  opt in "${search_options[@]}"
			do
				case $REPLY in
				1)
				echo "Please enter the Company Name you want to search for:"
				read searchCompany
				exec $SCRIPT_FINDBIZ "$searchCompany" "$REPLY"	#1st parameter is the search criteria , second parameter is the chosen option which will be used to determine
				;;											#what column to search in the file
				2)
				echo "Please enter the Contact Name you wish to search by:"
				read searchContact
				exec $SCRIPT_FINDBIZ "$searchContact" "$REPLY"
				;;
				3)
				echo "Please enter the address you wish to search by:"
				read searchAddress
				exec $SCRIPT_FINDBIZ "$searchAddress" "$REPLY"
				;;
				4)
				echo "Please enter the phone number you wish to search by:"
				read searchNumber
				exec $SCRIPT_FINDBIZ "$searchNumber" "$REPLY"
				;;
				5)
				echo "Please enter the the email address you wish to search by:"
				read searchEmail
				exec $SCRIPT_FINDBIZ "$searchEmail" "$REPLY"
				;;
				6) 
				echo "Returning to Main Menu"
				echo
				exec ./Menu
				;;
				*)
				echo "invalid option $REPLY"
				;;
				esac 
			done
		break;;
	4)	echo "GoodBye!"
		break
		;;
	*) echo "invalid option $REPLY"
	;;
	esac
done

