#!/bin/bash

# Alt+# to show line numbers
# This script will present the user with a command line menu.
# This menuw ill allow the user to select from AddBiz, RmBiz and FindBiz 
# This will also allow the user to email any or all of the companies listed in the Address Book

# chmod 755 Menu to give execute permissions on file
echo
echo
echo "Welcome to AddressBook"
echo "----------------------"
echo
# Create variables with the script to execute for each option

SCRIPT_ADDBIZ="./AddBiz"
SCRIPT_REMBIZ="./RmBiz"
SCRIPT_FINDBIZ="./FindBiz"


# Different options for the Menu and sub menus

main_options=("Add a Business" "Remove a Business" "Find a Business" "Send Email" "Quit")
search_options=("Search by Business Name" "Search by Contact Name" "Search by Address" "Search by Phone Number" "Search by Email" "Return to Main Menu" ) 
email_options=("Send Email to Individual Business" "Send Email to all Businesses" "Return to Main Menu")
PS3='Choose a number to select the option: '


# Main Menu
select opt in "${main_options[@]}"
do

echo

	case $REPLY  in
	1)
		echo "You have chosen to Add a Business"
			echo
			echo "Please enter the Company Name:"
			read companyName
			echo
			echo "Please enter the Business Contacts Full Name:"
			read contactName
			echo
			echo "Please enter their address:"
			read address
			echo
			echo "Please enter their phone number:"
			read phoneNumber
			echo
			echo "Please enter their email address:"
			read email
			echo
			echo "The details you entered are $companyName , $contactName , $address , $phoneNumber , $email  "
			echo "Adding to the AddressBook now.."
		#Call the AddBiz file 
		exec $SCRIPT_ADDBIZ "[$companyName]" "[$contactName]" "[$address]" "[$phoneNumber]" "[$email]"
		;;
	2)
		echo "You have chosen to Remove a Business"
		exec $SCRIPT_REMBIZ
		;;
	3)
		echo "You have chosen to Find a Business"
		echo
		echo
		# Sub Menu to select the search criteria
		select  opt in "${search_options[@]}"
			do
				case $REPLY in
				1)
				echo "Please enter the Company Name you want to search for:"
				read searchCompany
				exec $SCRIPT_FINDBIZ "$searchCompany" "$REPLY"	#1st parameter is the search criteria , second parameter is the chosen option which will be used to determine
				;;											#what column to search in the file
				2)
				echo "Please enter the Contact Name you wish to search by:"
				read searchContact
				exec $SCRIPT_FINDBIZ "$searchContact" "$REPLY"
				;;
				3)
				echo "Please enter the address you wish to search by:"
				read searchAddress
				exec $SCRIPT_FINDBIZ "$searchAddress" "$REPLY"
				;;
				4)
				echo "Please enter the phone number you wish to search by:"
				read searchNumber
				exec $SCRIPT_FINDBIZ "$searchNumber" "$REPLY"
				;;
				5)
				echo "Please enter the the email address you wish to search by:"
				read searchEmail
				exec $SCRIPT_FINDBIZ "$searchEmail" "$REPLY"
				;;
				6) 
				echo "Returning to Main Menu"
				echo
				exec ./Menu
				;;
				*)
				echo "invalid option $REPLY"
				;;
				esac 
			done
		break;;
	4)	echo "You have selected Send Email"
		# Sub Menu to select email option
		select  opt in "${email_options[@]}"
			do
				case $REPLY in
				1)
				echo
				echo "You have chosen to send an email to an individual Business"
				echo "Please enter the company name you wish to email:"
				read emailCompany
				echo
				echo "You want to email $emailCompany"
				cat BusinessDetails | awk -v pattern="$emailCompany" -F "] " ' tolower($1) ~ tolower(pattern) '
				email=$(cat BusinessDetails | awk -v pattern="$emailCompany" -F "] " ' tolower($1) ~ tolower(pattern) ' | awk -F "] " ' { print $5 } ') # Save the value of the email address
				#echo "The email address is $email"
				#remove square brackets from email
				emailAddress=$(echo $email | tr -d '[' | tr -d ']' )
				#echo "Actual email address is  $emailAddress" 
				echo
				echo "Please enter the email subject:"
				read emailSubject
				#echo "The email subject is $emailSubject"
				echo
				echo "Please enter the email body:"
				read emailBody
				#echo "The email body you entered is $emailBody"
				#send email here
				echo "$emailBody" | mail -s "$emailSubject" $emailAddress
				;;
				2)
				echo "You have chosen to email all companies"
				#  Below shows number of lines in the file
				#  wc -l < BusinessDetails
				#  loop through each line number and get send the email to each member in the file
				echo
				echo "Please enter the email Subject:"
				read emailSubject
				echo
				echo "Please enter the email body:"
				echo
				read emailBody
				echo
				noOfBus=$(wc -l < BusinessDetails )
					while [ $noOfBus -gt 0 ]
					do
						emailAddresses=$(sed -n "${noOfBus}p"  BusinessDetails | awk -F "] " ' {print $5 } ' | tr -d '[' | tr -d ']' )
						echo $emailBody | mail -s "emailSubject" $emailAddresses
						noOfBus=$[$noOfBus - 1 ]
						echo "Email Sent to " $emailAddresses
					done
				echo "Email sending complete"
				echo
				exec ./Menu
				;;
				3)
				echo "Returning to Main Menu"
				echo
				exec ./Menu
				;;
				*)
				echo "invalid option $REPLY"
				;;
				esac 
			done
		break;;

	5)	echo "GoodBye!"
		break
		;;
	*) echo "invalid option $REPLY"
	;;
	esac
done

