#!/bin/bash

# This script will remove all business's information from the AddressBook based on a particular businesses name or contacts name



#Search for the business the user requests to remove, then ask them to confirm they wish to delete the records shown on screen

SCRIPT_MAINMENU="./Menu"


echo

remove_options=("Remove a Business based on Company Name" "Remove a Business based on Company Contact" "Return to Main Menu")
PS3='Choose a number to select the option: '



select opt in "${remove_options[@]}"
do

echo

	case $REPLY  in
	1) echo "You have chosen to remove a business based on Company Name"
	   echo "Please enter the Company Name you wish to remove"
	   echo 
	   read companyName
	   echo
	   #Using the same logic in findBiz, search for the company Name in column 1 of the Business Details file
	   echo "Are you sure you want to remove this business? (y/n)"
	   cat BusinessDetails | awk -v pattern="$companyName" -F "] " ' tolower($1) ~ tolower(pattern) ' 
	   echo 
	   read confirmed
		if [ "$confirmed" =  "y" ]
		then
		echo "Removing Business..... "
		fi
	   ;;

	2) echo "You have chosen to remove a business based on Contact Name"
	   echo "Please enter the Contact Name you wish to remove:"
	   read contactName
           cat BusinessDetails | awk -v pattern="$contactName" -F "] " ' tolower($2) ~ tolower(pattern) ' 
	   echo 
	   echo "Are you sure you want to remove this Business?" 
	   ;;
	3) 
	  echo "Returning to Main Menu"
	  echo
	  exec ./Menu
	  ;;
	*)
	  echo "invalid option $REPLY"
	  ;;
	esac 
done
