#!/bin/bash

# This script will remove all business's information from the AddressBook based on a particular businesses name or contacts name



#Search for the business the user requests to remove, then ask them to confirm they wish to delete the records shown on screen

SCRIPT_MAINMENU="./Menu"


echo

remove_options=("Remove a Business based on Company Name" "Remove a Business based on Company Contact" "Return to Main Menu")
PS3='Choose a number to select the option: '



select opt in "${remove_options[@]}"
do

echo

	case $REPLY  in
	1) 
	echo "You have chosen to remove a business based on Company Name"
	echo "Please enter the Company Name you wish to remove"
	echo 
	read companyName
	echo
	#Using the same logic in findBiz, search for the company Name in column 1 of the Business Details file
	#echo "Are you sure you want to remove this business? (y/n)"
	#cat BusinessDetails | awk -v pattern="$companyName" -F "] " ' tolower($1) ~ tolower(pattern) ' 
	lineToRemove=$(cat BusinessDetails | awk -v pattern="$companyName" -F "] " ' tolower($1) ~ tolower(pattern) ')
	if [ -z "$lineToRemove" ]
		then
		echo "There is no Business matching that criteria"
		exec $SCRIPT_MAINMENU 
	else
	echo "Are you sure you want to remove this Business?"
	echo "lineToRemove"
	echo
	fi
	read confirmed
	if [ "$confirmed" =  "y" ]
		then
		echo "Removing Business..... "
		lineToRemove=$(cat BusinessDetails | awk -v pattern="$companyName" -F "] " ' tolower($1) ~ tolower(pattern) ') # Save the value to remove in a variable 
		echo "Removed $lineToRemove"
		#This doesnt work because I have [] within theh variable sed -i -r "$lineToRemove"'d' BusinessDetails
		#To get around this, use grep -F (to interpret as a fixed string) and -v to return everything except the business you want to remove, and redirect to a new file
		#Use the file of the same name and over write it
       	        grep -F -v "$lineToRemove" BusinessDetails >BusinessDetails.bak
		mv BusinessDetails.bak BusinessDetails
		exec $SCRIPT_MAINMENU
	elif [ "$confirmed" = "n" ]
		then
		exec ./RmBiz
	fi
	;;

	2) 
	echo "You have chosen to remove a business based on Contact Name"
	echo "Please enter the Contact Name you wish to remove:"
	read contactName
	lineToRemove=$(cat BusinessDetails | awk -v pattern="$contactName" -F "] " ' tolower($2) ~ tolower(pattern) ')
	if [ -z "$lineToRemove" ]
		then
		echo "There is no Business matching that criteria"
		exec $SCTIPT_MANIMENU
	else
		echo
		echo "Are you sure you want to remove this business? (y/n)"
        	#cat BusinessDetails | awk -v pattern="$contactName" -F "] " ' tolower($2) ~ tolower(pattern) ' 
		echo $lineToRemove
		echo
	fi
	read confirmed
	if [ "$confirmed" = "y" ]
		then
		echo "Removing Business...."
		echo "Removed $lineToRemove"
		grep -F -v "$lineToRemove" BusinessDetails >BusinessDetails.bak
		mv BusinessDetails.bak BusinessDetails
		exec $SCRIPT_MAINMENU
	elif [ "$confirmed" = "n" ]
		then
		exec ./RmBiz
	fi
	;;
	3) 
	echo "Returning to Main Menu"
	echo
	break
	;;
	*)
	echo "invalid option $REPLY"
	;;
	esac 
done

./Menu
